services:
  app:
    image: macdap-backend
    container_name: iot-backend
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DEBUG: app
    restart: no
